/**
  ******************************************************************************
  * @file    main.c
  * @author  Ac6
  * @version V1.0
  * @date    01-December-2013
  * @brief   Default main function.
  ******************************************************************************
*/

#include <ILI9341_Driver.h>
#include "main.h"
#include "stm32f0xx.h"
#include "stm32f0308_discovery.h"

//#include "ILI9341_Driver.c"
			
/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);

int main(void)
{

	/* MCU Configuration----------------------------------------------------------*/

	/* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	HAL_Init();

	/* Configure the system clock */
	SystemClock_Config();

	/* Initialize all configured peripherals */
	MX_GPIO_Init();
	GPIOC-> MODER |= (1<<16);

	//ILI_test();
	//return 0;
	/* =============Initialization=============== */
	ILI9341_Init();
	ILI9341_Set_Rotation(0);
	//GPIOC-> ODR |= (1<<8);
	HAL_Delay(500);
	//GPIOC-> ODR &= ~(1<<8);
	ILI9341_Fill_Screen(RED);
	GPIOC-> ODR &= ~(1<<8);

	HAL_Delay(500);
	ILI9341_Fill_Screen(GREEN);
	GPIOC-> ODR &= ~(1<<8);
	//GPIOC-> ODR |= (1<<8);
	HAL_Delay(500);
	ILI9341_Fill_Screen(BLUE);
	GPIOC-> ODR &= ~(1<<8);
	//GPIOC-> ODR &= ~(1<<8);
	HAL_Delay(500);
	//ILI9341_Fill_Screen(BLACK);
	//GPIOC-> ODR &= ~(1<<8);
	//GPIOC-> ODR |= (1<<8);
	HAL_Delay(500);

	 /* ===============Draw menu================= */
	//Display_Menu();

	GPIOC-> ODR &= ~(1<<8);
	while(1){
		for (int i=0; i< 500000; i++);
			GPIOC-> ODR |= (1<<8);
		for (int i=0; i< 500000; i++);
			GPIOC-> ODR &= ~(1<<8);

		//Display_Menu();
	}
}

void SystemClock_Config(void)
// This is NOT from the tutorial
// This was generated by STM32CubeMX
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL12;
  RCC_OscInitStruct.PLL.PREDIV = RCC_PREDIV_DIV1;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }
  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
}

/** Pinout Configuration
*/
static void MX_GPIO_Init(void)
{
	// CS to PA2
	// RESET to PA0
	// DC to PA1
	// MOSI to PA7
	// SCK to PA5
	// LED to 3V
	// MISO to PA6
	GPIO_InitTypeDef GPIO_InitStruct;

	/* GPIO Ports Clock Enable */
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_GPIOB_CLK_ENABLE();
	__HAL_RCC_GPIOC_CLK_ENABLE();
	__HAL_RCC_GPIOD_CLK_ENABLE();
	//__HAL_RCC_GPIOE_CLK_ENABLE();

	GPIO_InitStruct.Pin 	= DC_Pin | CS_Pin | RESET_Pin;
	GPIO_InitStruct.Mode 	= GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull 	= GPIO_NOPULL;
	GPIO_InitStruct.Speed 	= GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

}

/**
  * @brief  This function is executed in case of error occurrence.
  * @param  file: The file name as string.
  * @param  line: The line in file as a number.
  * @retval None
  */
void _Error_Handler(char *file, int line)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  while(1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
